commercetools/commercetools-sdk-java-v2

commercetools/import-api-default/build.gradle, commercetools/import-api-default/src/test/java/com/commerctools/importer/defaultconfig/ProductTypeImportIntegrationTest.java
@dpasdar I extracted this very pragmatic (`Thread.sleep(...)` 😁 ) integration test for the issue #62 you reported. And it works for me 😄  Would be great if you could take a look at my test 😄
=> Add intwegration test to reproduce issue.

README.md, commercetools/commercetools-api-default/src/test/java/commercetools/misc/UserAgentHeaderTest.java, commercetools/commercetools-api-default/src/test/java/commercetools/oauth/AnonymousSessionAuthIntegrationTest.java, commercetools/commercetools-api-default/src/test/java/commercetools/oauth/ClientCredentialsTokenSupplierIntegrationTests.java, commercetools/commercetools-api-default/src/test/java/commercetools/oauth/GlobalCustomerPasswordAuthIntegrationTest.java, commercetools/commercetools-api-default/src/test/java/commercetools/utils/CommercetoolsTestUtils.java, commercetools/import-api-default/src/test/java/com/commerctools/importer/defaultconfig/ImportApiTestUtils.java
=> Replace legacy urls with new urls.

commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/MiddlewareTest.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/defaultconfig/ApiFactory.java, commercetools/commercetools-sdk-java-importapi/src/main/java/com/commercetools/importapi/defaultconfig/ImportApiFactory.java, commercetools/commercetools-sdk-java-ml/src/main/java/com/commercetools/ml/defaultconfig/MLApiRootFactory.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/AuthenticationToken.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ClientFactory.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/MiddlewareFactory.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/http/OAuthHandler.java, rmf/rmf-java-base/src/test/java/io/vrap/rmf/base/client/AuthenticationTokenTest.java, rmf/rmf-java-base/src/test/java/io/vrap/rmf/base/client/http/OAuthHandlerTest.java
Add option to include custom userAgent
=> Test Reauth on 401

commercetools/commercetools-okhttp-client3/src/main/java/com/commercetools/http/okhttp3/CtOkHttp3Client.java, commercetools/commercetools-okhttp-client4/src/main/java/com/commercetools/http/okhttp4/CtOkHttp4Client.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/cleanup/DeleteEverythingIntegrationTest.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/utils/CommercetoolsTestUtils.java
=> use FQCN for okhttp classes

commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/PagedQueryResourceRequest.java
fixes #169 
For your consideration @jenschude @alex-ct 
Just noticed 3eaa725 which may mitigate the mentioned issue by a series of casting.
=> add add* methods to PagedQueryResourceRequest

commercetools/commercetools-sdk-compat-v1/src/main/java/com/commercetools/compat/CompatClient.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/custom_object/CustomObjectIntegrationTests.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/custom_object/GenericCustomObject.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/custom_object/GenericCustomObjectBuilder.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/custom_object/GenericCustomObjectImpl.java, commercetools/internal-docs/src/main/java/com/commercetools/docs/meta/GeneralConcept.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ApiHttpClient.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ApiHttpClientImpl.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ApiMethod.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ResponseSerializer.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ResponseSerializerImpl.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/SerializerOnlyApiHttpClient.java
=> support custom deserialization per request

commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/ConcurrentModificationTest.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/ExceptionTest.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/error/ApiHttpExceptionFactory.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/error/BadRequestException.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/error/ConcurrentModificationException.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/error/ErrorResponseException.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/defaultconfig/ApiRootBuilder.java
Add BadRequest and ConcurrentModificationException for api module
=> Add ApiHttpExceptionFactory

commercetools/commercetools-sdk-java-api/build.gradle, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/ConcurrentModificationTest.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ConcurrentModificationMiddleware.java
=> Add concurrent modification middleware

Migration.md, commercetools/commercetools-sdk-compat-v1/src/integrationTest/java/com/commercetools/migration/Retry.java, commercetools/commercetools-sdk-compat-v1/src/test/java/com/commercetools/compat/CompatibilityTest.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/AuthEndpointsTest.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/MiddlewareTest.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/request_errors/CategoryErrorHandlingIntegrationTests.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/defaultconfig/ApiRootBuilder.java, commercetools/commercetools-sdk-java-api/src/test/java/com/commercetools/ExampleTest.java, commercetools/commercetools-sdk-java-history/src/main/java/com/commercetools/history/defaultconfig/HistoryApiRootBuilder.java, commercetools/commercetools-sdk-java-importapi/src/main/java/com/commercetools/importapi/defaultconfig/ImportApiRootBuilder.java, commercetools/commercetools-sdk-java-ml/src/main/java/com/commercetools/ml/defaultconfig/MLApiRootBuilder.java, commercetools/internal-docs/src/main/java/com/commercetools/docs/meta/ClientTuning.java, commercetools/internal-docs/src/main/java/com/commercetools/docs/meta/Middlewares.java, commercetools/internal-docs/src/test/java/example/ExamplesTest.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ClientBuilder.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/error/HttpExceptionFactory.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/http/FailsafeRetryPolicyBuilderOptions.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/http/HttpStatusCode.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/http/RetryMiddleware.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/http/RetryRequestMiddleware.java, rmf/rmf-java-base/src/test/java/io/vrap/rmf/base/client/ApiHttpResponseTest.java, rmf/rmf-java-base/src/test/java/io/vrap/rmf/base/client/http/RetryMiddlewareTest.java
add option to customise retryMiddlewarePolicy
=> add option to handle failures in RetryMiddleware

commercetools/commercetools-sdk-java-api/src/test/java/com/commercetools/DecorateTest.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ApiMethod.java, rmf/rmf-java-base/src/test/java/io/vrap/rmf/base/client/ApiMethodTest.java
=> add decorate method to ApiMethod

commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/product/AttributeAccessor.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/product/AttributesAccessor.java, commercetools/commercetools-sdk-java-api/src/test/java/com/commercetools/AttributesTest.java, commercetools/commercetools-sdk-java-api/src/test/resources/attributes.json
add test for accessing nested attributes
=> add support for nested attributes to AttributesAccessor

rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ApiHttpHeaders.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/http/InternalLoggerMiddlewareImpl.java, rmf/rmf-java-base/src/test/java/io/vrap/rmf/base/client/http/InternalLoggerMiddlewareTest.java
=> add time information to the logger middleware

commercetools/commercetools-apachehttp-client/src/main/java/com/commercetools/http/apachehttp/ApacheHttpClientSupplier.java, commercetools/commercetools-apachehttp-client/src/main/java/com/commercetools/http/apachehttp/CtApacheHttpClient.java, commercetools/commercetools-apachehttp-client/src/main/resources/META-INF/services/io.vrap.rmf.base.client.ExecutorHttpClientSupplier, commercetools/commercetools-async-http-client/src/main/java/com/commercetools/http/asynchttp/AsyncHttpClientSupplier.java, commercetools/commercetools-async-http-client/src/main/java/com/commercetools/http/asynchttp/CtAsyncHttpClient.java, commercetools/commercetools-async-http-client/src/main/resources/META-INF/services/io.vrap.rmf.base.client.ExecutorHttpClientSupplier, commercetools/commercetools-okhttp-client3/src/main/java/com/commercetools/http/okhttp3/CtOkHttp3Client.java, commercetools/commercetools-okhttp-client3/src/main/java/com/commercetools/http/okhttp3/OkHttp3ClientSupplier.java, commercetools/commercetools-okhttp-client3/src/main/resources/META-INF/services/io.vrap.rmf.base.client.ExecutorHttpClientSupplier, commercetools/commercetools-okhttp-client4/src/main/java/com/commercetools/http/okhttp4/CtOkHttp4Client.java, commercetools/commercetools-okhttp-client4/src/main/java/com/commercetools/http/okhttp4/OkHttp4ClientSupplier.java, commercetools/commercetools-okhttp-client4/src/main/resources/META-INF/services/io.vrap.rmf.base.client.ExecutorHttpClientSupplier, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/defaultconfig/ApiRootBuilder.java, rmf/okhttp-client/src/main/java/io/vrap/rmf/okhttp/VrapOkHttpClientSupplier.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/BaseHttpClientSupplier.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ClientBuilder.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ExecutorHttpClientSupplier.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/HttpClientBase.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/HttpClientSupplier.java
- add builder methods to customize ExecutorService to be used for HTTP client and OAuth middlewares
=> add builder methods to configure executor services for http and oauth

api-java-mixin.raml
- add convert methods customfields & references to their drafts
=> add convert methods customfields & references to their drafts

commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/product/ProductDataLike.java, commercetools/commercetools-sdk-java-api/src/test/java/com/commercetools/ProductTest.java
- fixes de-/serialization of ProductDataLike objects
=> fix ProductDataLike serialization

commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/ConcurrentModificationTest.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/type/TypeFixtures.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/type/TypeIntegrationTests.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/utils/CommercetoolsTestUtils.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/json/CustomFieldDeserializer.java
- fix deserialization of custom fields with value node `key`
=> fix deserialization of customfields with value node key

commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/defaultconfig/ApiRootBuilder.java, commercetools/commercetools-sdk-java-history/src/main/java/com/commercetools/history/defaultconfig/HistoryApiRootBuilder.java, commercetools/commercetools-sdk-java-importapi/src/main/java/com/commercetools/importapi/defaultconfig/ImportApiRootBuilder.java, commercetools/commercetools-sdk-java-ml/src/main/java/com/commercetools/ml/defaultconfig/MLApiRootBuilder.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ClientBuilder.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/http/QueueMiddleware.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/http/QueueRequestMiddleware.java
- add configuration methods for the QueueMiddleware to the client builders
=> add configuration methods for the queue middleware

commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/cart/CartsFixtures.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/order/OrderIntegrationTests.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/order/OrdersFixtures.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/product/ProductFixtures.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ConcurrentModificationMiddlewareImpl.java
- fix exception in ConcurrentModificationMiddleware with delete requests
=> add test for order update

api-java-mixin.raml, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/models/common/Address.java, commercetools/commercetools-sdk-java-api/src/test/java/com/commercetools/AddressTest.java
- add helper to compare Addresses without the ID
=> add helper method equalsIgnoreId to Address

api-java-mixin.raml, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/WithKey.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/Draft.java
- add WithKey and Draft interface
=> add WithKey and Draft interface

api-java-mixin.raml, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/ConcurrentModificationTest.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/product_type/ProductTypeFixtures.java, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/client/ByProjectKeyProductTypesByIDDelete.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ApiDeleteMethod.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ConcurrentModificationDeleteRetryHandler.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/DeleteApiMethod.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/RetryHandler.java
- add retry handler for API delete methods
=> add retry handler for delete methods

commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ProjectApiRoot.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ProjectScopedApiRoot.java, commercetools/commercetools-sdk-java-history/src/integrationTest/java/com/commercetools/history/client/ProjectApiRootTest.java, commercetools/commercetools-sdk-java-history/src/main/java/com/commercetools/history/client/ProjectApiRoot.java, commercetools/commercetools-sdk-java-history/src/main/java/com/commercetools/history/client/ProjectScopedApiRoot.java, commercetools/commercetools-sdk-java-importapi/src/integrationTest/java/com/commercetools/importapi/client/ProjectApiRootTest.java, commercetools/commercetools-sdk-java-importapi/src/main/java/com/commercetools/importapi/client/ProjectApiRoot.java, commercetools/commercetools-sdk-java-importapi/src/main/java/com/commercetools/importapi/client/ProjectScopedApiRoot.java, commercetools/commercetools-sdk-java-ml/src/integrationTest/java/com/commercetools/api/client/ProjectApiRootTest.java, commercetools/commercetools-sdk-java-ml/src/main/java/com/commercetools/ml/client/ProjectApiRoot.java, commercetools/commercetools-sdk-java-ml/src/main/java/com/commercetools/ml/client/ProjectScopedApiRoot.java
add test to check projectApiRoot supports all project subresources
=> add interface for ProjectApiRoot

api-java-mixin.raml, build.gradle, buildSrc/src/main/kotlin/com/commercetools/sdk/plugins/MigrationInfoPlugin.kt, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/models/api_client/ApiClient.java, commercetools/internal-docs/src/main/java/com/commercetools/docs/meta/MigrationModelClassMapping.java, commercetools/internal-docs/src/test/java/example/CommandMigrationTest.java, rmf/okhttp-client/build.gradle
=> add mapping of v1 SDK commands to v2 request builders

commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/common/CurrencyUtils.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/common/DefaultCurrencyUnits.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/common/MoneyUtil.java, commercetools/commercetools-sdk-java-api/src/test/java/com/commercetools/MoneyTest.java, commercetools/commercetools-sdk-java-api/src/test/resources/price.json
=> fix class cast exception for MoneyUtils

rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/utils/CompletableFutureUtils.java, rmf/rmf-java-base/src/test/java/io/vrap/rmf/base/client/utils/CompletableFutureUtilsTest.java
- added the CompletableFutureUtils from the v1 SDK
=> add CompletableFutureUtils

build.gradle, commercetools/commercetools-monitoring-newrelic/build.gradle, commercetools/commercetools-monitoring-newrelic/src/main/java/com/commercetools/monitoring/newrelic/NewRelicSolutionInfo.java, commercetools/commercetools-monitoring-newrelic/src/main/resources/META-INF/services/io.vrap.rmf.base.client.SolutionInfo, examples/springmvc/build.gradle, examples/springmvc/src/main/java/com/commercetools/sdk/examples/springmvc/config/MonitoringConfig.java, gradle-scripts/subproject-config.gradle, rmf/rmf-java-base/build.gradle, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ClientBuilder.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/SolutionInfo.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/SolutionInfoService.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/UserAgentUtils.java
- Add information about NewRelic middleware to user agent string
=> add SolutionInfo interface for more user agent details

commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/cart/CartQueryTests.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/PagedQueryResourceRequest.java
=> fix query predicate helper method in PagedQueryResourceRequest

api-java-mixin.raml, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/cart/CartQueryTests.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/customer/CustomerQueryTests.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/payment/PaymentQueryTests.java, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/client/ByProjectKeyApiClientsGet.java, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/client/ByProjectKeyAsAssociateByAssociateIdBusinessUnitsGet.java, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/client/ByProjectKeyAssociateRolesGet.java, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/client/ByProjectKeyAttributeGroupsGet.java, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/client/ByProjectKeyBusinessUnitsGet.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ByProjectKeyApiClientsGetMixin.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ByProjectKeyAsAssociateByAssociateIdBusinessUnitsGetMixin.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ByProjectKeyAssociateRolesGetMixin.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ByProjectKeyAttributeGroupsGetMixin.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ByProjectKeyBusinessUnitsGetMixin.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/PagedQueryResourceRequest.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/predicates/query/CombinationQueryPredicate.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/predicates/query/ComparablePredicateBuilder.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/predicates/query/ContainerQueryPredicate.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/predicates/query/ContainsPredicateBuilder.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/predicates/query/EmptyPredicateBuilder.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/predicates/query/EqualityPredicateBuilder.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/predicates/query/InequalityPredicateBuilder.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/predicates/query/IsInPredicateBuilder.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/predicates/query/NotEqualPredicateBuilder.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/predicates/query/VariableQueryPredicate.java, commercetools/commercetools-sdk-java-api/src/test/java/com/commercetools/api/predicates/query/QueryTests.java, commercetools/internal-docs/src/test/java/example/ExamplesTest.java
- improvements to the query predicate builders
=> support query predicate variables

api-java-mixin.raml, buildSrc/src/main/kotlin/com/commercetools/sdk/plugins/GraphQLTask.kt, commercetools/commercetools-graphql-api/src/integrationTest/java/com/commercetools/graphql/api/TestQuery.java, commercetools/commercetools-graphql-api/src/main/java/com/commercetools/graphql/api/ByProjectKeyGraphqlQuery.java, commercetools/commercetools-graphql-api/src/main/java/com/commercetools/graphql/api/GraphQLRequest.java, commercetools/commercetools-graphql-api/src/main/java/com/commercetools/graphql/api/GraphQLRequestBuilder.java, commercetools/commercetools-graphql-api/src/main/java/com/commercetools/graphql/api/GraphQLResponse.java, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/client/ByProjectKeyGraphqlRequestBuilder.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ProjectRequestBuilder.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ApiHttpResponse.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ApiMethod.java
- GraphQL module improved to read the operation result without explicitly providing the request object
=> add feature to extract the GraphQL result data directly

.github/workflows/ci.yml, build.gradle, gradle-scripts/jacoco.gradle, gradle.properties
=> use gradle toolchain config

api-java-mixin.raml, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/models/cart_discount/CartDiscountValue.java, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/models/cart_discount/CartDiscountValueAbsolute.java, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/models/cart_discount/CartDiscountValueFixed.java, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/models/cart_discount/CartDiscountValueGiftLineItem.java, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/models/cart_discount/CartDiscountValueRelative.java, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/models/channel/ChannelReference.java, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/models/product/ProductReference.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/cart_discount/CartDiscountValueAbsoluteMixin.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/cart_discount/CartDiscountValueFixedMixin.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/cart_discount/CartDiscountValueGiftLineItemMixin.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/cart_discount/CartDiscountValueMixin.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/cart_discount/CartDiscountValueRelativeMixin.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/cart_discount/GenericCartDiscountValueMixin.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/channel/ChannelReferenceMixin.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/product/ProductReferenceMixin.java, commercetools/commercetools-sdk-java-api/src/test/java/com/commercetools/CartDiscountTest.java
=> add toDraft helper methods for CartDiscountValue and subtypes

.github/workflows/ci.yml, build.gradle, commercetools/commercetools-sdk-java-api/build.gradle, gradle-scripts/jacoco.gradle, gradle-scripts/subproject-config.gradle, rmf/rmf-java-base/build.gradle
=> avoid rebuild for example test

commercetools/commercetools-sdk-compat-v1/src/main/java/com/commercetools/compat/CompatClient.java, commercetools/commercetools-sdk-compat-v1/src/main/java/com/commercetools/compat/CompatRequest.java, commercetools/commercetools-sdk-compat-v1/src/main/java/com/commercetools/compat/CompatSphereClient.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/DecoratorTest.java, commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/MultiTenantTest.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ConcurrentModificationDeleteRetryHandler.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ConcurrentModificationRetryHandler.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ApiHttpClient.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ApiHttpClientImpl.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ApiMethod.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ClientRequestCommand.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ContextApiHttpClientImpl.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/CreateHttpRequestCommand.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/RequestCommand.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/SerializerOnlyApiHttpClient.java, rmf/rmf-java-base/src/test/java/io/vrap/rmf/base/client/ApiMethodTest.java
=> add support for decorated ApiHttpClient

build.gradle, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/common/LocalizedString.java, commercetools/commercetools-sdk-java-api/src/test/java/com/commercetools/LocalizedStringTest.java
=> fix localeValues method for LocalizedStrings

commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/SimplePagedQueryResourceRequest.java, commercetools/commercetools-sdk-java-api/src/test/java/com/commercetools/PagedQueryRequestTest.java
=> fix predicate variable helper methods

rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ApiHttpClient.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/AsyncApiClient.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/BodyApiMethod.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/CompletableFutureApiClient.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/HttpRequestCommand.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/StringBodyApiMethod.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/TypeApiMethod.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/TypeBodyApiMethod.java
=> preparations for HttpRequestCommand

.github/workflows/ci.yml, commercetools/commercetools-sdk-java-api/build.gradle, commercetools/commercetools-sdk-java-api/src/test/java/com/commercetools/MainMethodMemoryLeakTest.java
=> add test for memory leaks

build.gradle, commercetools/commercetools-sdk-java-api/src/test/java/com/commercetools/MainMethodMemoryLeakTest.java, commercetools/internal-docs/src/main/java/com/commercetools/docs/meta/ClientTuning.java, gradle-scripts/subproject-config.gradle, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/utils/json/JsonUtils.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/utils/json/modules/deserializers/LocalDateDeserializationModule.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/utils/json/modules/deserializers/ZonedDateTimeDeserializer.java, rmf/rmf-java-base/src/test/java/io/vrap/rmf/base/client/utils/json/CommercetoolsObjectMapperTests.java
Fix parsing of dates and date times exceeding year 9999
=> fix issue with dates exceeding year 9999

commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/customer/CustomerMixin.java
- mixin methods for customer class
=> add mixin helper methods for customer

build.gradle, commercetools/internal-docs/src/main/java/com/commercetools/docs/meta/GraphQL.java, commercetools/internal-docs/src/main/java/com/commercetools/docs/meta/Logging.java, src/main/javadoc/overview.html
=> add ToC taglet to overview page

.github/workflows/ci.yml, .github/workflows/release.yml, examples/maven-okhttp3/pom.xml, examples/maven-okhttp4/pom.xml, examples/spring-newrelic/build.gradle, examples/spring-otel/build.gradle, examples/spring/build.gradle, gradle.properties
=> use a fixed version for the examples

api-java-mixin.raml, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/models/message/MessagePayload.java, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/models/subscription/MessageDeliveryPayload.java, commercetools/commercetools-sdk-java-api/src/main/java-generated/com/commercetools/api/models/subscription/MessageDeliveryPayloadImpl.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/subscription/MessageDeliveryPayloadMixin.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/subscription/MessagePayloadMixin.java, commercetools/commercetools-sdk-java-api/src/test/java/com/commercetools/MessagePayloadTest.java, commercetools/commercetools-sdk-java-api/src/test/resources/messagedeliverypayload.json
=> deserialize message payload helper

.github/workflows/ci.yml, .github/workflows/docs.yml, commercetools/commercetools-sdk-java-api/src/integrationTest/java/cleanup/DeleteEverythingIntegrationTest.java
=> add concurrency to CI workflows

.github/workflows/ci.yml
=> fix renovate builds

commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/defaultconfig/ApiRootBuilder.java, commercetools/commercetools-sdk-java-history/src/main/java/com/commercetools/history/defaultconfig/HistoryApiRootBuilder.java, commercetools/commercetools-sdk-java-importapi/src/main/java/com/commercetools/importapi/defaultconfig/ImportApiRootBuilder.java, commercetools/internal-docs/src/main/java/com/commercetools/docs/meta/Logging.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/ClientBuilder.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/http/ErrorLogFormatter.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/http/InternalLoggerMiddleware.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/http/InternalLoggerMiddlewareImpl.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/http/LogFormatter.java, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/http/ResponseLogFormatter.java
=> add option to customise log formats

commercetools/commercetools-sdk-java-api/src/integrationTest/java/commercetools/ConcurrentModificationTest.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ConcurrentModificationDeleteRetryHandler.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/ConcurrentModificationRetryHandler.java
=> fix RetryHandler class cast exception

Best-practices.md
- Remove lines that don't describe best practices.
=> Remove the incorrect lines

commercetools/internal-docs/src/main/java/com/commercetools/docs/meta/Querying.java
Highlight the integration tests section in the javadoc.
=> Highlight tests in the docs

commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/defaultconfig/ServiceRegion.java, commercetools/commercetools-sdk-java-history/src/main/java/com/commercetools/history/defaultconfig/ServiceRegion.java
=> [DEVX-344] add missing service regions

.github/workflows/ci.yml, examples/spring-dynatrace-oneagent/Dockerfile, licenses/commercetools-async-http-client/index.json, licenses/commercetools-graphql-api/index.json, licenses/commercetools-http-client/index.json, licenses/commercetools-monitoring-datadog/index.json, licenses/commercetools-monitoring-newrelic/index.json, licenses/commercetools-monitoring-opentelemetry/index.json, licenses/commercetools-reactornetty-client/index.json, licenses/commercetools-sdk-compat-v1/index.json, licenses/index.json
pin dockerfile for spring dynatrace example- [ ] Changeset added
=> use codecov GH action

gradle-scripts/extensions.gradle, licenses/commercetools-apachehttp-client/index.json, licenses/commercetools-async-http-client/index.json, licenses/commercetools-graphql-api/index.json, licenses/commercetools-http-client/index.json, licenses/commercetools-javanet-client/index.json, licenses/commercetools-monitoring-datadog/index.json, licenses/commercetools-monitoring-newrelic/index.json, licenses/commercetools-monitoring-opentelemetry/index.json, licenses/commercetools-okhttp-client3/index.json, licenses/commercetools-okhttp-client4/index.json, licenses/commercetools-reactornetty-client/index.json, licenses/commercetools-sdk-compat-v1/index.json, licenses/commercetools-sdk-java-api/index.json, licenses/commercetools-sdk-java-history/index.json, licenses/commercetools-sdk-java-importapi/index.json, licenses/index.json, licenses/rmf-java-base/index.json
=> update SLF4J to 2.0

commercetools/commercetools-monitoring-datadog/src/main/java/com/commercetools/monitoring/datadog/DatadogResponseSerializer.java, commercetools/commercetools-monitoring-datadog/src/main/java/com/commercetools/monitoring/datadog/statsd/DatadogResponseSerializer.java, commercetools/commercetools-monitoring-newrelic/src/main/java/com/commercetools/monitoring/newrelic/NewrelicResponseSerializer.java
Switch (de)serialization metrics to the correct meaning: https://stackoverflow.com/questions/3316762/what-is-deserialize-and-serialize-in-json
=> Switch (de)serialization metrics to the correct meaning

commercetools/commercetools-monitoring-datadog/src/main/java/com/commercetools/monitoring/datadog/DatadogMiddleware.java, commercetools/commercetools-monitoring-datadog/src/main/java/com/commercetools/monitoring/datadog/DatadogResponseSerializer.java, commercetools/commercetools-monitoring-datadog/src/test/java/example/ResponseSerializerTest.java, commercetools/commercetools-monitoring-datadog/src/test/java/example/TelemetryMiddlewareTest.java, rmf/rmf-java-base/src/test/java/io/vrap/rmf/base/client/http/TelemetryMiddlewareTest.java
=> add test for Datadog middleware

commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/defaultconfig/ServiceRegion.java, commercetools/commercetools-sdk-java-history/src/main/java/com/commercetools/history/defaultconfig/ServiceRegion.java, commercetools/commercetools-sdk-java-importapi/src/main/java/com/commercetools/importapi/defaultconfig/ServiceRegion.java
=> update service regions

commercetools/commercetools-sdk-java-api/src/test/java/com/commercetools/CartDiscountTest.java, gradle-scripts/extensions.gradle, licenses/commercetools-sdk-compat-v1/index.json, licenses/index.json, rmf/rmf-java-base/src/main/java/io/vrap/rmf/base/client/utils/json/JsonUtils.java
=> Fix deserialization if subtype discriminator is missing

examples/spring/README.md, examples/spring/src/main/java/com/commercetools/sdk/examples/spring/config/CtpSecurityConfig.java, examples/spring/src/main/java/com/commercetools/sdk/examples/spring/config/MeClientFilter.java, examples/spring/src/main/java/com/commercetools/sdk/examples/spring/service/CtpClientBeanService.java, examples/spring/src/main/java/com/commercetools/sdk/examples/spring/service/CtpReactiveAuthenticationManager.java, examples/spring/src/main/java/com/commercetools/sdk/examples/spring/web/AppController.java
I will add the custom auth and api url for other examples later sometimes later. I created a task for it: https://commercetools.atlassian.net/browse/DEVX-495
=> Add option to provide custom auth and api url for spring example project

commercetools/commercetools-apachehttp-client/build.gradle, commercetools/commercetools-apachehttp-client/src/main/java/com/commercetools/http/apachehttp/ApacheHttpClientSolutionInfo.java, commercetools/commercetools-apachehttp-client/src/main/java/com/commercetools/http/apachehttp/CtApacheHttpClient.java, commercetools/commercetools-apachehttp-client/src/main/resources/META-INF/services/io.vrap.rmf.base.client.SolutionInfo, licenses/commercetools-apachehttp-client/index.json, licenses/index.json
=> Update Apache AsyncHttpClient

commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/QueryAll.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/client/QueryUtils.java
=> [DEVX-322] QueryAll allows different field than id to be used

.github/workflows/semgrep.yml
=> add semgrep workflow

commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/json/ApiModule.java, commercetools/commercetools-sdk-java-api/src/main/java/com/commercetools/api/models/subscription/DeliveryPayloadMixin.java, commercetools/commercetools-sdk-java-api/src/test/java/com/commercetools/MessagePayloadTest.java
=> fix Delivery discriminators

gradle-scripts/extensions.gradle
=> revert junit-jupiter

.github/workflows/release-snapshot.yml, .github/workflows/release.yml, gradle-scripts/publishing.gradle
=> update Maven Release process
